# Generated by Django 5.2.5 on 2025-08-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='header',
            name='menu_item1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='menu_item2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='menu_item3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='menu_item4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
