# Generated by Django 5.2.5 on 2025-10-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
