# Generated by Django 5.2.5 on 2025-10-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_rename_description_product_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
