# Generated by Django 5.2.5 on 2025-10-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trending',
        ),
    ]
