# Generated by Django 5.2.5 on 2025-11-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_remove_product_created_at_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='with_Size',
            field=models.BooleanField(default=False, help_text='0=default, 1=Hidden'),
        ),
    ]
