# Generated by Django 5.2.5 on 2025-11-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_product_with_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='with_Size',
            new_name='one_Size',
        ),
    ]
