# Generated by Django 5.2.5 on 2025-11-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_rename_with_size_product_one_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='one_Size',
            new_name='one_size',
        ),
    ]
