# Generated by Django 5.2.5 on 2025-11-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_rename_one_size_product_one_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='one_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
