# Generated by Django 5.2.5 on 2025-11-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_colorproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproduct',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colorproducts/'),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='selling_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
