# Generated by Django 5.2.5 on 2025-12-07 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_colorproduct_description_colorproduct_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.category'),
        ),
    ]
