# Generated by Django 5.2.5 on 2025-12-07 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_colorproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.category'),
        ),
    ]
