# Generated by Django 5.2.5 on 2025-12-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_alter_colorproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproduct',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='colorproducts/'),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='colorproducts/'),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='colorproducts/'),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='colorproducts/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='colorproduct',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
