# Generated by Django 5.2.5 on 2025-12-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_colorproduct_image1_colorproduct_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='placeholder',
            field=models.ImageField(blank=True, null=True, upload_to='placeholder/'),
        ),
        migrations.AddField(
            model_name='category',
            name='placeholderLabel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
