# Generated by Django 5.2.5 on 2025-12-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_category_placeholder_category_placeholderlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='placeholder/')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='placeholder',
        ),
        migrations.RemoveField(
            model_name='category',
            name='placeholderLabel',
        ),
    ]
