# Generated by Django 5.2.5 on 2026-01-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_placeholder_remove_category_placeholder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
    ]
