# Generated by Django 5.2.5 on 2026-03-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
