# Generated by Django 5.2.5 on 2026-04-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_alter_userprofile_role_alter_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproduct',
            name='one_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
