# Generated by Django 5.2.5 on 2026-04-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0032_colorproduct_one_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorproduct',
            name='one_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='one_size',
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='size',
            field=models.CharField(blank=True, default='one size', max_length=20, null=True),
        ),
    ]
