# Generated by Django 5.2.5 on 2026-04-05 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0033_remove_colorproduct_one_size_remove_product_one_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('size', models.CharField(blank=True, default='one size', max_length=20, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ColorProduct',
        ),
    ]
