# Generated by Django 5.2.5 on 2026-04-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_productsize_item_delete_colorproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='sizeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('productSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.productsize')),
            ],
        ),
    ]
