# Generated by Django 5.2.5 on 2026-04-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0035_sizeterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeterm',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
