# Generated by Django 5.2.5 on 2026-04-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0036_sizeterm_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeterm',
            name='acronym',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
