# Generated by Django 5.2.5 on 2026-05-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0039_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.userprofile'),
        ),
    ]
