# Generated by Django 5.2.5 on 2026-07-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0042_order_savedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaddress',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('cod', 'Cash on Delivery')], max_length=10, null=True),
        ),
    ]
