# Generated by Django 5.2.5 on 2026-07-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0044_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(blank=True, default='active', null=True),
        ),
    ]
