# Generated by Django 5.2.5 on 2026-07-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0045_alter_voucher_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='is_active',
        ),
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=20, null=True),
        ),
    ]
