# Generated by Django 5.2.5 on 2026-07-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0047_voucher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
