# Generated by Django 5.2.5 on 2026-07-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0049_order_discount_order_shippingfee_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingFee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
