# Generated by Django 5.2.5 on 2026-08-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0050_alter_order_shippingfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='cart', max_length=20, null=True),
        ),
    ]
