# Generated by Django 5.2.5 on 2026-08-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0051_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, default='cart', max_length=20, null=True),
        ),
    ]
