# Generated by Django 5.2.5 on 2026-08-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0053_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit or Debit CardCard'), ('cod', 'Cash on Delivery')], max_length=100),
        ),
    ]
